### ISSUE TITLE
Is there a way to export variables?

### ISSUE THREAD

**Issue by math2001** [zombieleet/async-bash#3]
I have a function like this:

```bash
function update_variables {
    export GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
}

function prompt {
  export PS1="$GIT_BRANCH \w $"
}
```

But, the variable `GIT_BRANCH` doesn't exits...

**Comment by zombieleet** [comment]
you have to execute `update_variable` function first, before prompt will be able to access it
